
export const FETCH_JOBS_POST_REQUEST="FETCH_JOBS_POST_REQUEST";
export const FETCH_JOBS_POST_SUCCESS="FETCH_JOBS_POST_SUCCESS";
export const FETCH_JOBS_POST_FAILURE="FETCH_JOBS_POST_FAILURE";

//apply for job on checked

export const ADD_JOBS_TO_APPLY="ADD_JOBS_TO_APPLY";
export const REMOVE_JOBS_FROM_APPLY="REMOE_JOBS_FROM_APPLY";
